monitors: [
IA1BPA01_H,
IA1BPB01_H,
IA3BPC01_H,
IA3BPC02_H,
IA3BPC03_H,
IB1BPC01_H,
IB1BPC02_H,
IB1BPC03_H,
ID1BPC01_H,
IA1BPA01_V,
IA1BPB01_V,
IA3BPC01_V,
IA3BPC02_V,
IA3BPC03_V,
IB1BPC01_V,
IB1BPC02_V,
IB1BPC03_V,
ID1BPC01_V,
IA1BPA01_PH,
IA1BPB01_PH,
IA3BPC01_PH,
IA3BPC02_PH,
IA3BPC03_PH,
IB1BPC01_PH,
IB1BPC02_PH,
IB1BPC03_PH,
ID1BPC01_PH,
IA1BPA01_I,
IA1BPB01_I,
IA3BPC01_I,
IA3BPC02_I,
IA3BPC03_I,
IB1BPC01_I,
IB1BPC02_I,
IB1BPC03_I,
ID1BPC01_I,
]
